// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ApproveClientEntryReducer from "../approve_client_entry_reducer";
import RequestRoomEntryReducer from "../request_room_entry_reducer";
import ResetRoomReducer from "../reset_room_reducer";

export type ApproveClientEntryParams = __Infer<typeof ApproveClientEntryReducer>;
export type RequestRoomEntryParams = __Infer<typeof RequestRoomEntryReducer>;
export type ResetRoomParams = __Infer<typeof ResetRoomReducer>;

