// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ApproveClientEntryReducer from "../approve_client_entry_reducer";
import EndSessionReducer from "../end_session_reducer";
import RequestRoomEntryReducer from "../request_room_entry_reducer";
import ResetRoomReducer from "../reset_room_reducer";
import SaveBlueprintReducer from "../save_blueprint_reducer";
import SeedExercisesReducer from "../seed_exercises_reducer";

export type ApproveClientEntryParams = __Infer<typeof ApproveClientEntryReducer>;
export type EndSessionParams = __Infer<typeof EndSessionReducer>;
export type RequestRoomEntryParams = __Infer<typeof RequestRoomEntryReducer>;
export type ResetRoomParams = __Infer<typeof ResetRoomReducer>;
export type SaveBlueprintParams = __Infer<typeof SaveBlueprintReducer>;
export type SeedExercisesParams = __Infer<typeof SeedExercisesReducer>;

