// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  blueprintId: __t.string().name("blueprint_id"),
  exerciseName: __t.string().name("exercise_name"),
  warmupFor: __t.string().name("warmup_for"),
  sets: __t.u32(),
  reps: __t.u32(),
  weight: __t.string(),
  isStaticHold: __t.bool().name("is_static_hold"),
  orderIndex: __t.u32().name("order_index"),
});
