// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  blueprintId: __t.string().primaryKey().name("blueprint_id"),
  roomId: __t.string().name("room_id"),
  name: __t.string(),
  targetGoal: __t.string().name("target_goal"),
  isActiveDayPlan: __t.bool().name("is_active_day_plan"),
});
