// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roomId: __t.string().primaryKey().name("room_id"),
  roomToken: __t.string().name("room_token"),
  ptName: __t.string().name("pt_name"),
  expectedClientName: __t.string().name("expected_client_name"),
  submittedClientName: __t.string().name("submitted_client_name"),
  clientStatus: __t.string().name("client_status"),
});
