// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  logId: __t.string().primaryKey().name("log_id"),
  roomId: __t.string().name("room_id"),
  timestamp: __t.string(),
  notes: __t.string(),
  completedExercisesJson: __t.string().name("completed_exercises_json"),
});
