// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Room = __t.object("Room", {
  roomId: __t.string(),
  roomToken: __t.string(),
  ptName: __t.string(),
  expectedClientName: __t.string(),
  submittedClientName: __t.string(),
  clientStatus: __t.string(),
});
export type Room = __Infer<typeof Room>;

