// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Blueprint = __t.object("Blueprint", {
  blueprintId: __t.string(),
  roomId: __t.string(),
  name: __t.string(),
  targetGoal: __t.string(),
  isActiveDayPlan: __t.bool(),
});
export type Blueprint = __Infer<typeof Blueprint>;

export const BlueprintExercise = __t.object("BlueprintExercise", {
  id: __t.string(),
  blueprintId: __t.string(),
  exerciseName: __t.string(),
  warmupFor: __t.string(),
  sets: __t.u32(),
  reps: __t.u32(),
  weight: __t.string(),
  isStaticHold: __t.bool(),
  orderIndex: __t.u32(),
});
export type BlueprintExercise = __Infer<typeof BlueprintExercise>;

export const ExerciseDictionary = __t.object("ExerciseDictionary", {
  exerciseId: __t.string(),
  name: __t.string(),
  category: __t.string(),
  targetMuscle: __t.string(),
  description: __t.string(),
});
export type ExerciseDictionary = __Infer<typeof ExerciseDictionary>;

export const Room = __t.object("Room", {
  roomId: __t.string(),
  roomToken: __t.string(),
  ptName: __t.string(),
  expectedClientName: __t.string(),
  submittedClientName: __t.string(),
  clientStatus: __t.string(),
  lastSessionNotes: __t.string(),
  lastSessionTimestamp: __t.string(),
});
export type Room = __Infer<typeof Room>;

export const SessionHistory = __t.object("SessionHistory", {
  logId: __t.string(),
  roomId: __t.string(),
  timestamp: __t.string(),
  notes: __t.string(),
  completedExercisesJson: __t.string(),
});
export type SessionHistory = __Infer<typeof SessionHistory>;

